export const GET_PAYMENTHISTORY_REQUEST = 'GET_PAYMENTHISTORY_REQUEST'
export const GET_PAYMENTHISTORY_SUCCESS = 'GET_PAYMENTHISTORY_SUCCESS'
export const GET_PAYMENTHISTORY_FAILURE = 'GET_PAYMENTHISTORY_FAILURE'